<?php

Route::group(['namespace' => "coordinator",'middleware' => 'coordinator'], function() {
    Route::get('phase', 'coordinatorController@get_phase');
    Route::get('subphase', 'coordinatorController@get_subphase');
    Route::get('event', 'coordinatorController@get_event');
    Route::post('/add_phase', 'coordinatorController@add_phase');
    Route::post('/add_subphase', 'coordinatorController@add_subphase');
    Route::post('/get_phase_option', 'coordinatorController@get_phase_option');
    Route::post('/add_event', 'coordinatorController@add_event');
    Route::post('/edit_subphase', 'coordinatorController@edit_subphase');
    Route::post('/edit_save_subphase', 'coordinatorController@edit_save_subphase');
    Route::post('/get_subphase_option', 'coordinatorController@get_subphase_option');
    Route::post('/edit_event', 'coordinatorCOntroller@edit_event');
    Route::post('/edit_save_event', 'coordinatorController@edit_save_event');
    Route::post('/edit_phase', 'coordinatorController@edit_phase');
    Route::post('/edit_save_phase', 'coordinatorController@edit_save_phase');
    Route::get('/add_student_to_programme','coordinatorController@add_student_to_programme');
    Route::post('/add_student','coordinatorController@add_student_prg');
    Route::get('/all_student','coordinatorController@get_all_student');
    Route::get('/add_student_to_subphase','coordinatorController@get_std_to_subphase');
    Route::post('/add_std_to_subphase','coordinatorController@add_std_to_subphase');
    Route::post('/add_std_to_subphase_csv','coordinatorController@add_std_to_subphase_csv');
    Route::post('/reject_request_coordinator','coordinatorController@reject_request');
    Route::post('/accept_request_coordinator','coordinatorController@accept_request');
    Route::post('/send_consent_form_reminder_std','coordinatorController@send_reminder_std');
    Route::get('/grading','coordinatorController@get_grading_page');
    Route::post('/get_students_for_grade','coordinatorController@get_students_for_grade');
    Route::get('/student_grading/{phase}/{subphase}','coordinatorController@get_coordinator_grading_page');
    Route::get('/coordinator_view_report/{std_sub_id}','coordinatorController@c_view_report');
    Route::post('/get_mentor_comment','coordinatorController@get_mentor_comment');
    Route::post('/save_grade_coordinator','coordinatorController@save_grade_coordinator');
    Route::post('/submit_grade_coordinator','coordinatorController@submit_grade_coordinator');
    Route::post('/coordinator_comment','coordinatorController@save_coordinator_comment');
    Route::get('/manage_faculties','coordinatorController@get_manage_faculties');
    Route::post('/add_faculties', 'coordinatorController@add_faculties_to_program');
    Route::post('/co_delete_faculties','coordinatorController@co_delete_faculties');
    Route::get('/manage_committee_events', 'coordinatorController@manage_committee_events' );
    Route::post('/se_save_start_end_date' , 'coordinatorController@se_save_deadline');
    Route::get('/committee','coordinatorController@get_committee');
    Route::post('/sub_exp_reminder','coordinatorController@sub_exp_reminder');
    Route::post('/start_bid_date','coordinatorController@start_bid_date');
    Route::post('/get_bid_requests','coordinatorController@get_bid_requests');
    Route::post('/save_final_committee','coordinatorController@save_final_committee');
    Route::post('/edit_committee','coordinatorController@edit_committee');
    Route::post('/edit_final_committee','coordinatorController@edit_final_committee');
    Route::post('/view_committee','coordinatorController@view_committee');
    Route::get('/email_template','coordinatorController@get_email_template');
    Route::post('/save_mail','coordinatorCOntroller@save_mail');
    Route::get('/create_committee','coordinatorController@get_create_committee');
    Route::post('/get_all_mentors','coordinatorController@get_all_mentors');
    Route::post('/save_final_committee_btech','coordinatorController@save_final_committee_btech');
    Route::post('/edit_committee_btech','coordinatorController@edit_committee_btech');
    Route::post('/edit_final_committee_btech','coordinatorController@edit_final_committee_btech');
    Route::post('/committee_grade','coordinatorController@get_committee_grades');
    Route::post('/committee_comment','coordinatorController@get_committee_comment');
    Route::post('/send_mail','coordinatorCOntroller@send_mail');
    Route::post('/send_mail_to_students','coordinatorCOntroller@bring_emails_of_students');
    Route::post('/get_mail_template_data','coordinatorController@get_mail_template_data');
    Route::get('/manage_deadline_for_event','coordinatorController@get_manage_deadline_for_event');
    Route::post('/show_student_subphase','coordinatorController@show_student_subphase');
    Route::post('/modify_student_deadline','coordinatorController@modify_student_deadline');
    Route::post('/fail_student_subphase','coordinatorController@fail_student_subphase');
    Route::post('/do_final_grading','coordinatorController@do_final_grading');
    Route::post('/modified_std_prog_data', 'coordinatorController@modified_std_data');
    Route::get('/consent_form_deadline','coordinatorController@get_consent_form_deadline');
    Route::post('/cf_save_start_end_date','coordinatorController@save_consent_form_deadline');
    Route::post('/give_std_subphase','coordinatorController@give_std_subphase');
    Route::post('/give_student_sub','coordinatorController@give_student_sub');
    Route::post('/get_faculty_list','coordinatorController@get_faculty_list');
    Route::post('/save_changed_mentor_subject_expert','coordinatorController@save_modified_mentor');
    Route::post('/subject_expert_reminder','coordinatorController@subject_expert_reminder');
    Route::post('/accept_on_behalf__of_se','coordinatorController@accept_on_behalf__of_se');
    Route::post('/reject_on_behalf__of_se','coordinatorController@reject_on_behalf__of_se');
    Route::post('/student_consent_form_deadline', 'coordinatorController@student_consent_form_deadline');
    Route::post('/remind_mentor_consent_form','coordinatorController@remind_mentor_consent_form');
    Route::get('/view_backend_email_template','coordinatorController@view_backend_email_template');
    Route::post('/get_backend_mail_template','coordinatorController@get_backend_mail_template');
});

